#!/usr/bin/env sh

sudo yabai --load-sa

yabai -m config layout bsp

yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

yabai -m config --space 5 top_padding 10
yabai -m config --space 5 bottom_padding 24

yabai -m config window_placement second_child

yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

yabai -m config window_shadow float

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_drop_action swap

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add title="Preferences$" manage=off
yabai -m rule --add title="Settings$" manage=off

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Toggle spaces 6-7 visibility based on display count
yabai -m signal --add event=display_added action='
  sketchybar --set space.6 drawing=on --set space.7 drawing=on
'
yabai -m signal --add event=display_removed action='
  sketchybar --set space.6 drawing=off --set space.7 drawing=off
'
