#!/bin/bash
osascript -e 'tell application "Ghostty"
    if it is running then
        tell application "System Events" to tell process "Ghostty" to click menu item "New Window" of menu "File" of menu bar 1
    else
        activate
    end if
end tell'
